ORG 0H ;THIS IS A DIRECTIVE,STATING START(ORIGIN) AT LOACTION 0
MOV R5,#25H
MOV R7,#34H
MOV A,#0; MNEMONICS PRODUCE OPCODES
ADD A,R5;
ADD A,R7;
HERE: SJMP HERE;LABEL FIELD ALLOWS A PROG TO REFER TO A LINE OF CODE BY NAME 
	END


